### ISSUE TITLE
Regenerate missing RTE magic image on rendering

### ISSUE THREAD

**Issue by agendartobias** [FriendsOfTYPO3/rtehtmlarea#15]
Hello, i have the same problem as here: https://forge.typo3.org/issues/56147

1. Insert a Magic Image in the RTE
2. "Look how nicely it is rendered on the FE"
3. Delete the image in processed directory
4. Reload the FE. Oh, a 404 image!
5. I can get rid of 404 Error if i save content again

Can you help me with this?

**Comment by Abdull** [comment]
Related: https://github.com/netresearch/t3x-rte_ckeditor_image/issues/25

**Comment by liayn** [comment]
This extension is marked as obsolete. We are not going tackle this issue anymore.
