### ISSUE TITLE
File, mail and external Links in IE11 and Edge

### ISSUE THREAD

**Issue by darthnorman** [FriendsOfTYPO3/rtehtmlarea#16]
When inserting link into text, nothing happens.

What I do: Mark some text, click on link symbol, choose a file, click on generate link.
(It does work with 'Pages', which is odd.)
What happens: The whole paragraph gets marked but no link is inserted.

Version: TYPO3 8.7.12, rtehtmlarea 8.7.1

**Comment by freshworkx** [comment]
I can confirm this behavior for TYPO3 8.7.19 / RteHtmlArea 8.7.1 in IE11 and Edge.
Also, if there is more than one Link, the JS-Selection goes wrong and update the first link instead of create a second new link. This behavior looks very similar to this one: https://forge.typo3.org/issues/84299

**Comment by ohader** [comment]
Confirmed
* IE11
  + link to page (having another link in the same paragraph) links the whole paragraph (`<p>`)
  + link to external URL jumps to beginning of paragraph without setting link
* Edge
  + link to page(s) seems to be working (different to IE11 behavior)
  + link to external URL jumps to beginning of paragraph without setting link (same as IE11 behavior)

**Comment by ohader** [comment]
Please test PR #29
