### ISSUE TITLE
ContextMenu Position in Typo3 8

### ISSUE THREAD

**Issue by pserrer** [FriendsOfTYPO3/rtehtmlarea#17]
In the current version of Typo3 8 the Context Menu is positioned on the wrong position.

It seems the position calculation inside ContextMenu.js isn't correct. I fixed it by changing line 229 to

    top: iframePosition.y + this.mousePosition.y - $(".module-body").scrollTop() - this.editor.iframe.document.body.scrollTop + 'px'

In addition to that, there's also a problem, if the path of your Typo3 installation isn't on the domains root. In this case, the path of clear.gif isn't correct. A simple solution would be to make the path relative and just change line 301 from `src: '/typo3...` to `src: '../typo3...`

**Comment by katywings** [comment]
The proposed change regarding "I fixed it by changing line 229 to..." worked for me too 👍 , thanks for your details in this issue :D
