### ISSUE TITLE
Page TSconfig overwrites my own page TSconfig

### ISSUE THREAD

**Issue by zauni** [FriendsOfTYPO3/rtehtmlarea#18]
Hi,

I have updated from TYPO3 7 to 8 and installed the rtehtmlarea extension, but now my "RTE.default.showButtons" configuration in my page TSconfig is overwritten by the TSconfig of this extension.

In a provider extension I have a `ext_localconf.php` where I load the page TSconfig with my RTE configuration:

```php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig(
    '<INCLUDE_TYPOSCRIPT: source="FILE:EXT:myprovider/Configuration/TypoScript/page-tsconfig.txt">'
);
```

I set the RTE.default.showButtons to for example `bold,italic,undo,redo,about,blockstyles,blockstylelabel,orderedlist`.

The only setting in rtehtmlarea is "defaultConfiguration" = "Minimal". With this setting, rtehtmlarea is loading its own page TSconfig `EXT:rtehtmlarea/Configuration/PageTSconfig/Advanced/pageTSConfig.txt`.  
Inside this file you are configuring RTE.default.showButtons to `bold,italic,undo,redo,about`.

And now just these 5 buttons are visible in the backend because it looks like your page TSconfig is loaded after mine and it "wins". When I comment everything in `EXT:rtehtmlarea/Configuration/PageTSconfig/Advanced/pageTSConfig.txt` my configuration is working just fine.

Should the advanced page TSconfig be empty (I could make a pull request) or can I change the order in which the TSconfig is applied? Or should I load my own TSconfig in a different way?

**Thanks for any help!**

**Comment by bmack** [comment]
Hi @zauni ,

ensure that your extension depends on EXT:RTEhtmlarea (via composer.json + ext_emconf.php), and ensure that it's loaded AFTER rtehtmlarea by checking your `typo3conf/PackageStates.php` file.

Hope that helps!

**Comment by zauni** [comment]
Thanks @bmack !

Now it's working like a charm 👍

**Comment by blueamerican** [comment]
I have the same problem without an extension. I have the page ts config code in the root page.
This should normally overwrite the extension ts config.
But it doesn't.
Any suggestions?

Can this issue be reopened?

**Comment by blueamerican** [comment]
i put my tsconfig in an extension.
