### ISSUE TITLE
HTMLArea is not defined

### ISSUE THREAD

**Issue by prdt3e** [FriendsOfTYPO3/rtehtmlarea#27]
Typo3: 8.7.20
rtehtmlarea: 8.7.1
Browser: Chrome (72.0.3626.121)

I have 6 editors on the page.
The first call works, then not more.
The bug is only in Chrome (72.0.3626.121).
It works in Firefox/IE.

It is reported:
HTMLArea is not defined HTMLArea.js: 125

Thanks

**Comment by ohader** [comment]
Confirmed

**Comment by prdt3e** [comment]
Puuuh that code is not easy.
HtmlArea and HTMLArea

**Comment by ohader** [comment]
Please test PR #29

**Comment by prdt3e** [comment]
Many Thanks.
It works perfectly.
I suspected something similar.
That's actually defined in RichTextElement.php 654 - weird mistake

**Comment by ohader** [comment]
Actually the definition in PHP is "correct" as well, however due to asynchronous processing via RequireJS it will happen that the resulting definition in HTML is executed too late.
