### ISSUE TITLE
Table header (thead) ignored

### ISSUE THREAD

**Issue by nicozerr** [FriendsOfTYPO3/rtehtmlarea#3]
Hi.

When I try to create a table with top and/or left header, the generated HTML code has no th-tags, nor thead-tag.
The only way to have a top header is to create a table without header, edit the first row, and define it as a header.
For a left header, it's worst: I have to edit each cell and define it as a row header.
It worked before on TYPO3 7.6, when rtehtmlarea was into sysext.

A little video of the problem: http://recordit.co/QCQJBWUQpa

I work with TYPO3 8.7.6 and the very last version of rtehtmlarea from your github.

**Comment by nicozerr** [comment]
Nobody can answer me ?

**Comment by bmack** [comment]
AFAIK there was no change regarding the `<thead>` and `<th>` tags in RTEhtmlarea between 8.7 and 7.6. Is it the same configuration?

**Comment by dnozdrin** [comment]
In the file /ext/rtehtmlarea/Resources/Public/JavaScript/Plugins/TableOperations.js on the line 1462 change
`var headers = params.f_headers;`
to
`var headers = params.typeof;`

**Comment by nicozerr** [comment]
Wouhou ! It works now ! Thank you very much !
