### ISSUE TITLE
File links in Edge not working  (TYPO3 v7.6.35)

### ISSUE THREAD

**Issue by DrillSergeant** [FriendsOfTYPO3/rtehtmlarea#34]
Hello guys

Using Edge, it is not possible to create file-links in RTE fields. We can reproduce this in all of our TYPO3 7.6.35 instances unsing Edge 17.17134

When clicking a file in the Link-Wizard Popup, we see a JS error "SCRIPT5022: HierachyRequestError" in the JS-Console:
![screenshot-2](https://user-images.githubusercontent.com/883552/57285560-bf276e00-70b3-11e9-9808-9a3c106b5934.png)

What can we do?

**Comment by bmack** [comment]
Hey @DrillSergeant ,

this repository is for HTMLarea v8 which is only compatible with TYPO3 v8 LTS. For TYPO3 v7 RTEHtmlArea was included in TYPO3 Core Repository with the latest public version 7.6.32, so 7.6.35 sounds like a version delivered by the ELTS program of typo3.com. Please contact TYPO3 GmbH for further assistance.

Thanks!
Benni.

**Comment by DrillSergeant** [comment]
Thanks I will do so
