### ISSUE TITLE
Custom table class does not work in TYPO3 v8.7

### ISSUE THREAD

**Issue by p-meyer** [FriendsOfTYPO3/rtehtmlarea#35]
I can choose my custom table class in the table property popup, but my choose will be ignored. When I use the Button "toogle text modus" I dont see the custom table class in the markup. Also in Frontend there only be the default class 'contenttable'.

TYPO3 v8.7
rtehtmlarea 8.7.2

**Comment by onlinenow** [comment]
The select field for the css classes is missing the name attribute. Thats the reason the class cant be assigned to the tabel. Apply the changes in the pull request and this should work again.

**Comment by p-meyer** [comment]
Fine. It works for me.
