### ISSUE TITLE
This extension contains documentation in Readme.rst and Documentation folder

### ISSUE THREAD

**Issue by sypets** [FriendsOfTYPO3/rtehtmlarea#37]
I realize this is happening with a lot of extensions but I find it a little unfortunate. 

People who visit GitHub see the Readme. People who visit [docs.typo3](https://docs.typo3.org/typo3cms/extensions/rtehtmlarea/) see the rendered documentation in `Documentation`. Which is up-to-date? Which should people contribute to. 

What some other extensions do, is just provide a short Readme and then link to the generated documentation on docs.typo3.org. 

You can - of course - do whatever you want.

**Comment by liayn** [comment]
What did you identify as documentation in the readme here? For me this rather reads like a general project description.

**Comment by liayn** [comment]
@sypets ping
