### ISSUE TITLE
RTE with Safari TYPO3 7.6

### ISSUE THREAD

**Issue by paul-keller** [FriendsOfTYPO3/rtehtmlarea#39]
With new Safari version RTE is not working in TYPO3 7.6 anymore.
Same Bug as with Chrome, see: https://github.com/FriendsOfTYPO3/rtehtmlarea/issues/26

**Comment by p-meyer** [comment]
Same Problem in TYPO3 v8.7.27 with rtehtmlarea v8.7.2

**Comment by julianstefanov** [comment]
You can use the patch from here: https://github.com/FriendsOfTYPO3/rtehtmlarea/pull/38

**Comment by paul-keller** [comment]
> You can use the patch from here: #38

Does not work for me. RTE still does not work in Safari

**Comment by stucki** [comment]
see #40 / https://github.com/FriendsOfTYPO3/rtehtmlarea/pull/40/commits/a20e23445ca760ba94ed06dca05266b6e22a25fb

This is a forward-port of the solution which is included in the 7.6.39 ELTS release.

**Comment by liayn** [comment]
@paul-keller Is this fixed with the information from above?

**Comment by paul-keller** [comment]
@liayn Problem is solved. RTE in Safari is working correctly with 7.6.40
