### ISSUE TITLE
Make Documentation Accessible

### ISSUE THREAD

**Issue by Chaoste** [FriendsOfTYPO3/rtehtmlarea#42]
Hey guys,

thanks for carrying on this project so far!

When trying to find the documentation for this extension, one may click on "Extension Manual" at the [extension page](https://extensions.typo3.org/extension/rtehtmlarea/) which is currently referring to a not existing documentation (probably from the original project). 

The new link should be [https://docs.typo3.org/p/friendsoftypo3/rtehtmlarea/master/en-us/](https://docs.typo3.org/p/friendsoftypo3/rtehtmlarea/master/en-us/). At least add it to your README so others can find this, too. 

Thank you!
Thomas

**Comment by bmack** [comment]
@liayn could you update the link on TER linking to the right docs?

**Comment by liayn** [comment]
@bmack Relayed via Slack doc-team channel, because I don't know how to do that. 🤷‍♂

**Comment by marble** [comment]
https://typo3.slack.com/archives/C028JEPJL/p1577620283011500?thread_ts=1577485344.010800&cid=C028JEPJL

**Comment by liayn** [comment]
Again checked the current state and requested support from the docs team to get this sorted out, finally.

**Comment by liayn** [comment]
Related issue:
https://github.com/TYPO3-Documentation/T3DocTeam/issues/126

**Comment by liayn** [comment]
The link now points to v8.7, which is not master, but better than 404
