### ISSUE TITLE
Editor not working in latest Safari and TYPO3 8.7.32

### ISSUE THREAD

**Issue by stephaniestief** [FriendsOfTYPO3/rtehtmlarea#43]
Editor isn't loading in latest Safari Version with TYPO3 8.7.32 

![image](https://user-images.githubusercontent.com/42339404/78329268-82911a80-7581-11ea-9594-651a11ce23fd.png)

**Comment by liayn** [comment]
Please post the version of Safari you are using. This is by the way not related to the TYPO3 version at all, simply to Safari itself.

**Comment by liayn** [comment]
Can you please download the lastest version here from git and try if it is still a problem?
There has been a fix with #26 which might solve this one too.

**Comment by liayn** [comment]
Just got a confirmation that latest master has this already fixed. Will create a release now. Should be available on TER shortly.

**Comment by stephaniestief** [comment]
Works perfectly! Thank you for the quick support.
