### ISSUE TITLE
After Chrome Update to `Version 91.0.4472.101` the RTE fields in the Backend don't work anymore

### ISSUE THREAD

**Issue by m41r** [FriendsOfTYPO3/rtehtmlarea#46]
After Chrome update to `91.0.4472.101` the RTE fields in the Backend don't work anymore and crash with an exception.

Affected Version: `Typo3 v7.6.32` (maybe any bugfix version)
Affected File: `/typo3/sysext/rtehtmlarea/Resources/Public/JavaScript/HTMLArea/Editor/Iframe.js`
Exception:
```
Iframe.js?bust=ea1f9be4e56ea26f5bfc6c6354b1067e497aa241:202 Uncaught TypeError: Cannot read property 'documentElement' of null
    at Iframe.initializeIframe (VM664 Iframe.js:202)
    at Iframe.render (VM664 Iframe.js:57)
    at Framework.render (VM661 Framework.js:75)
    at new Framework (VM661 Framework.js:45)
    at Editor.createFramework (VM639 Editor.js:189)
    at Editor.generate (VM639 Editor.js:175)
    at VM639 Editor.js:179
```
Did some of those fixes caused this? 
https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop.html

Can someone confirm?

**Comment by m41r** [comment]
For the record, this happens maybe because some "Same Origin" stuff and Chrome changed something in that way... idk.

> If the iframe and the iframe's parent document are Same Origin, returns a Document (that is, the active document in the inline frame's nested browsing context), else returns null.

Source: https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument

**Comment by paavo** [comment]
Looks like the Issue was already fixed some times ago in ELTS 7.6.

**Comment by paavo** [comment]
I have a pretty similar Bug in Safari 14.1.1 on OS X 11.4. 

![Screen Shot 2021-06-11 at 15 28 13](https://user-images.githubusercontent.com/1118783/121693727-af1bbd00-cac9-11eb-92b0-d8c763ea84f8.png)

**Comment by m41r** [comment]
@paavo That sounds more like #26 ... for me it looks different:
 
![image](https://user-images.githubusercontent.com/14954406/121849256-6a6f6c00-cceb-11eb-80b2-01d173b89098.png)

**Comment by apgl64** [comment]
Hello !
Do a backup of your file : Resources/Public/JavaScript/HTMLArea/Editor/Editor.js
Update this file by the last on : https://github.com/FriendsOfTYPO3/rtehtmlarea/blob/b7ba8bf46e0e7266e8b01afe2551de73186f074f/Resources/Public/JavaScript/HTMLArea/Editor/Editor.js
Clear Caches
It works for me on TYPO3 7.6

**Comment by apgl64** [comment]
For TYPO3 6.2 : Go to /typo3/sysext/rtehtmlarea/htmlarea and edit file "htmlarea.js"
Go to line 2187 or find line begin by `src: Ext.isGecko`
Replace
`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'popups/blank.html')`
or
`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? (Ext.isChrome ? 'about:blank;' : 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' ): HTMLArea.editorUrl + 'popups/blank.html')`
by
`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit || Ext.isChrome ? '' : HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')`
That's all ! :)

**Comment by m41r** [comment]
@apgl64 i can confirm, that snippet works perfectly, thank you very much! 🚀

i close this issue, because this won't be fixed for Typo3 v7 branch anyway ... for all the others with this problem, i hope this helps you.

**Comment by liayn** [comment]
@m41r If you provide a PR, I'll happily merge it

**Comment by m41r** [comment]
@liayn you mean for Typo3  `v8`? Well that's not necessary, i think, because this Repo has already the Bugfix merged, namely this line:
https://github.com/FriendsOfTYPO3/rtehtmlarea/blob/b7ba8bf46e0e7266e8b01afe2551de73186f074f/Resources/Public/JavaScript/HTMLArea/Editor/Editor.js#L217

For my Typo3 v7 instance, i just patched it via `composer patches` and it worked ... no merge needed. 
Or did I understand you wrong?

**Comment by liayn** [comment]
Great then.
