### ISSUE TITLE
Wrong Links for pageids

### ISSUE THREAD

**Issue by mmirsch** [FriendsOfTYPO3/rtehtmlarea#5]
When using pageIdSelector to enter TYPO3 page-ids directly, the generated links are not working any more.

I fixed this by entering these lines in "rtehtmlarea\Resources\Public\JavaScript\RteLinkBrowser.js":

        if (parseInt(input) == input) {
            input = 't3://page?uid=' + input;
        }

Here my Patch:

 `--- /typo3conf/ext/rtehtmlarea/Resources/Public/JavaScript/RteLinkBrowser.js	(revision )`
 `+++ /typo3conf/ext/rtehtmlarea/Resources/Public/JavaScript/RteLinkBrowser.js	(revision ) `
 `@@ -96,6 +96,11 @@ `
  `		delete attributes.target; `
  `		delete attributes.params; `
 ` `
 `+        // replace links from PageIdInputField  `
 `+        if (parseInt(input) == input) { `
 `+            input = 't3://page?uid=' + input; `
 `+        } `
 `+ `
  `        RteLinkBrowser.plugin.createLink( `
  `			input + curParams, `
  `			curTarget, `

**Comment by liayn** [comment]
Which TYPO3 version are you using?

**Comment by mmirsch** [comment]
I am not sure, maybe TYPO3 7.6

**Comment by liayn** [comment]
This is rather strange then, because the `t3://page` syntax came with TYPO3 version 8.3

**Comment by mmirsch** [comment]
Ok, I found it.
It was in TYPO3-extension rtehtmlarea-8.7.0.

**Comment by liayn** [comment]
I released version 8.7.3 today. can you please verify if this is still a problem in the latest version?

**Comment by mmirsch** [comment]
The problem still exista, as you didn't change the javascript file.

Here the patch again:

Index: www.local.typo3.org/typo3conf/ext/rtehtmlarea/Resources/Public/JavaScript/RteLinkBrowser.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- www.local.typo3.org/typo3conf/ext/rtehtmlarea/Resources/Public/JavaScript/RteLinkBrowser.js    (date 1585910886209)
+++ www.local.typo3.org/typo3conf/ext/rtehtmlarea/Resources/Public/JavaScript/RteLinkBrowser.js    (date 1585910886209)
@@ -96,6 +96,10 @@
         delete attributes.target;
         delete attributes.params;
 
+        if (parseInt(input) == input) {
+            input = 't3://page?uid=' + input;
+        }
+
         RteLinkBrowser.plugin.createLink(
             input + curParams,
             curTarget,

**Comment by liayn** [comment]
@mmirsch Thanks for the info. Would you mind creating a Pull-Request instead of posting it inline in the comments?

**Comment by mmirsch** [comment]
Ok, how do I do that?

**Comment by mmirsch** [comment]
Ok, found a way to do the pull request abd I hope I did it correctly.

**Comment by liayn** [comment]
Do you see the same problem if you set such a link in normal link field (e.g. header link)?

**Comment by mmirsch** [comment]
I cannot even activate this in TYPO3 8.7.
Do you know, if it's possible an how?
i tried:

TCEMAIN.linkHandler.page {
    configuration {
        pageIdSelector.enabled = 1
    }
}

In page tsconfig, but when I checked source code I found that this option is only working for recordlists.

**Comment by liayn** [comment]
You are right. I looked up the code now too and this feature is indeed RTE-only.

Your fix is working as expected, but actually I consider this a core-bug, which needs to be fixed for any RTE. The appropriate place would be this:
https://github.com/TYPO3/TYPO3.CMS/blob/master/Build/Sources/TypeScript/recordlist/Resources/Public/TypeScript/PageLinkHandler.ts#L53

I'll create a patch for core, but since v8 is already in ELTS mode, I can't guarantee this will still be fixed for v8.

**Comment by liayn** [comment]
Will continue in https://forge.typo3.org/issues/82942
