### ISSUE TITLE
rtehtmlarea isn't working on newest Chrom version

### ISSUE THREAD

**Issue by MarkusGehrig** [FriendsOfTYPO3/rtehtmlarea#50]
Hey Everyone

The htmlarea isn't working on the newest Chrom version 91.0.4472.114. Check the last digest when testing, with version 91.0.4472.77 it is still working. 

It looks like that the htmlarea tries to load, but gets into an endless loop for the redactor. 

TYPO3 Version is 8.7.36 / 8.7.40 and htmlarea version is 8.7.3

**Comment by fheyer** [comment]
Yes, i can confirm that Chrome ver. 91.0.4472.106 on Mac already has the problem. Using HTMLArea 8.7.3 on Typo3 8.7.32.

**Comment by MarkusGehrig** [comment]
Can some one please create a new release?

**Comment by liayn** [comment]
Did so yesterday
