### ISSUE TITLE
Missing documentation: options from EXT:rtehtmlarea still work for rte_ckeditor but documentation was not transferred.

### ISSUE THREAD

**Issue by bj0hn** [FriendsOfTYPO3/rtehtmlarea#54]
The options to configure the RTE from EXT:rtehtmlarea are still there and can be used with EXT:rte_ckeditor, but the documentation was not transferred. 
Infos like 
https://docs.typo3.org/p/friendsoftypo3/rtehtmlarea/main/en-us/Configuration/PageTsconfig/classesAnchor/Index.html 
and more!

Is there a reason for this?

```
RTE {
	default {
		preset = nn_bsa
		buttons.link {
			options.removeItems = folder
			properties.class.allowedClasses = 
		}
		classesAnchor {
			page {
				class = link-internal
				type = page
				titleText = 
				target =
			}

```

**Comment by liayn** [comment]
Definitely no reason I could remember.

I guess it should be added then somewhere here
https://docs.typo3.org/c/typo3/cms-rte-ckeditor/main/en-us/Configuration/Reference.html#config-ref
or here
https://docs.typo3.org/m/typo3/reference-tsconfig/main/en-us/PageTsconfig/Rte.html#pagetsrte

But this configuration should be done in YAML nowadays, so not sure if this old configuration really works as expected with current ckeditor.

**Comment by liayn** [comment]
moved it over to the documentation repo

**Comment by bj0hn** [comment]
I had also described the problem here before:

https://forge.typo3.org/issues/98244#change-475774

The options are still available! 
If the better way now is to write this in a yaml file this should be documented best with examples. 

I don't know how the yaml syntax looks like.
